### ISSUE TITLE
ical4j erroneously escapes DQUOTE

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#105]
See https://github.com/ical4j/ical4j/issues/641
I think it's only a one-letter PR + some tests :)

Maybe you can have a look at it? @ArnyminerZ

If there are questions just post here or we also can have a talk. Did you already check out and compile / run ical4j tests before?

Depends on https://github.com/ical4j/ical4j/pull/641
Depends on https://github.com/ical4j/ical4j/pull/643

**Comment by ArnyminerZ** [comment]
See https://github.com/ical4j/ical4j/pull/643

**Comment by ArnyminerZ** [comment]
I think this can now be closed. Reopen otherwise

**Comment by rfc2822** [comment]
I think the fix is not already in ical4android, we'll have to wait for the next ical4j version.

Let's close it as soon as we use an ical4j version that actually contains the fix.

**Comment by rfc2822** [comment]
We can create a PR that updates ical4j to 3.2.13 to close this issue.
