### ISSUE TITLE
Support COMMENT for tasks

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#127]
We could support `COMMENT` with the Comment field for TasksOrg-compatible tasks:

https://github.com/bitfireAT/ical4android/blob/93262f53c2f6e200f73ec9e0ca876e9b120841ae/opentasks-contract/src/main/java/org/dmfs/tasks/contract/TaskContract.java#L1543-L1565

- [x] Add a `comment` field to `Task`.
- [x] `Task` should be able to read the `COMMENT` property into the `comment` field
- [x] `Task` should be able to generate the `COMMENT` property from the `comment` field
- [x] `DmfsTask`: generate `COMMENT` data row (probably with language `null`) from `Task.comment` field
- [x] `DmfsTask`: process `COMMENT` data row and fill `Task.comment` field from it

**Comment by rfc2822** [comment]
I hope this is even supported by tasks.org… @sunkup interested in giving it a try?

**Comment by abaker** [comment]
Tasks.org doesn't try to sync comments yet, but I'd like to

**Comment by sunkup** [comment]
> @sunkup interested in giving it a try?

Sure, I wonder which servers support the COMMENT field already though? Seems like [nextcloud (tasks) does not](https://github.com/nextcloud/tasks/issues/109) ?

**Comment by rfc2822** [comment]
> Sure, I wonder which servers support the COMMENT field already though? Seems like [nextcloud (tasks) does not](https://github.com/nextcloud/tasks/issues/109) ?

When more clients support it, I guess other clients have a better chance of adopting it. As far as I know, jtx Board also supports it.
