### ISSUE TITLE
Ignore recurrence information in exceptions of recurring events

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#135]
> It's not necessary, but some providers add it and that's why, for example, apple calender synchronises correctly, despite the redundancy of the "RRULE".
>
>I think it would be good to ignore the "RRULE" of modified events

For more information, see the discussion:

_Originally posted by @JorisBodin in https://github.com/bitfireAT/davx5-ose/discussions/558#discussioncomment-8494027_

We could possibly do it in `EventValidator.repair()`. What do you think @sunkup?

**Comment by sunkup** [comment]
If this really is a problem ... we can remove RRULEs that are part of event exceptions (events with a RECURRENCE-ID) if their SEQUENCE is bigger than 0. 

Is this what you want to do? This would be the first time we "repair" something that seems to be perfectly valid by the standard.

**Comment by rfc2822** [comment]
> Is this what you want to do? This would be the first time we "repair" something that seems to be perfectly valid by the standard.

Do you mean RRULEs in the exception of RRULEs are valid? I don't think so, even if it's not mentioned explicitly. But apart from not having seen this at any time (and in the original discussion it was clearly a mistake in the iCalendar), the standard speaks about the exception being "individual instances", and with RRULE it's not an indivdual instance anymore.

**Comment by sunkup** [comment]
> Do you mean RRULEs in the exception of RRULEs are valid? I don't think so, even if it's not mentioned explicitly. But apart from not having seen this at any time (and in the original discussion it was clearly a mistake in the iCalendar), the standard speaks about the exception being "individual instances", and with RRULE it's not an indivdual instance anymore.

Yes, I don't think it's good or smart to have though. I used a validator to check, but that one could of course also be either wrong or just lenient about it. 

And you are making a fair point, the standard speaking about individual instance an RRULE instance not being a genuine "individual" instance.

**Comment by rfc2822** [comment]
> Yes, I don't think it's good or smart to have though. I used a validator to check, but that one could of course also be either wrong or just lenient about it.

Maybe they don't had the idea that this could happen and just ignore it ;)

> I wonder why apple and thunderbird have no issue with this though.

As I have seen, at least Apple just ignores it.

> If this really is a problem ... we can remove RRULEs that are part of event exceptions (events with a RECURRENCE-ID) if their SEQUENCE is bigger than 0.

I don't understand how it's related to the `SEQUENCE`?

**Comment by sunkup** [comment]
> I think it would be good to ignore the "RRULE" of modified events

You were speaking of "modified events" here. But I can see now, that you mean the RRULE exception is the modification itself.  

> I don't understand how it's related to the `SEQUENCE`?

Good, then we don't need it :)

**Comment by rfc2822** [comment]
> You were speaking of "modified events" here. But I can see now, that you mean the RRULE exception is the modification itself.

Ah yes, I mean the RRULE of exceptions of recurring events 😃
