### ISSUE TITLE
recurrenceSetsToAndroidString, androidStringToRecurrenceSet: handle multiple entries separated by newline

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#30]
- [x] Check whether Android can have multiple entries in the recurrence set columns (RDATE, …), possibly with different time zones.
- [ ] Handle these cases accordingly in recurrenceSetsToAndroidString
- [ ] and androidStringToRecurrenceSet

As far as I have found out, the Android [RDATE field is a list of lines, separated by new-line (`\n`)](https://android.googlesource.com/platform/frameworks/opt/calendar/+/refs/heads/master/src/com/android/calendarcommon2/RecurrenceSet.java). Every line looks like this:

* `[Europe/Vienna;]YYYYMMDDThhmmss[Z],YYYYMMDDThhmmss[Z]` for non-all-day events
* `YYYYMMDD,YYYYMMDD` for all-day events

Currently we don't handle multiple lines with multiple time zones in our conversion methods.

**Comment by rfc2822** [comment]
In the branch for this issue, I have added

- a test that proves that Android supports multi-line RDATEs with different time zones, and
- tests for desired functionality.

@ArnyminerZ Can you please create a draft PR for this branch? If I do, I won't be able to review (because Github thinks I'd review myself)

**Comment by ArnyminerZ** [comment]
Yup, I think it's all clear 😄

**Comment by rfc2822** [comment]
This would be nice to have, but it's highly specific and almost nobody uses it. If this problem occurs in the real world, we'll re-open.
