### ISSUE TITLE
Android always expects RRULE UNTIL to be in UTC format

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#54]
Currently, we insert RRULE with UNTIL as it comes from the event (as defined in RFC 5445).

However, some code parts of the Android calendar provider seem to [always expect UNTIL to be in UTC format](https://android.googlesource.com/platform/frameworks/opt/calendar/+/refs/tags/android-12.1.0_r27/src/com/android/calendarcommon2/RecurrenceProcessor.java#93), as specified in the obsolete RFC 2445.

So RRULE UNTIL should always be converted to UTC before inserting it into the calendar provider. Not doing so might result in losing the last occurrence.

Side note: ical4j parses UNTIL in the system default timezone and not in the DTSTART timezone. This may cause further problems…

**Comment by sunkup** [comment]
I am tad confused by this. Ical4j seems to express UNTIL in UTC time straight away after parsing it. See https://github.com/ical4j/ical4j/blob/develop/src/main/java/net/fortuna/ical4j/model/Recur.java#L283. 

What makes you think it goes into the calendar provider in non UTC format - is it reproducible?

**Comment by rfc2822** [comment]
I couldn't reproduce it.
