### ISSUE TITLE
Accept tasks with DUE=DTSTART

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#70]
See bitfireAT/davx5-ose#243. Proposed solution:

> As the DUE>DTSTART constraint is enforced by OpenTasks (which is not recommended anymore), we could drop DTSTARTs that are >= DUE only when OpenTasks is the tasks backend. So if jtx Board and tasks.org accept tasks with DTSTART=DUE, we could sync such tasks to those backends as they are. Then everything including the alarms should be retained. For OpenTasks, we keep everything as it is because it's legacy code and will be removed sooner or later anyway.

Also relevant for @TechbeeAT @patrickunterwegs (jtx Board UI changes for DTSTART=DUE as discussed in chat).

**Comment by rfc2822** [comment]
I'd like to technically accept as much as possible (also DTSTART>DUE) but I think the user should not be allowed to enter such invalid values in the UI.

**Comment by abaker** [comment]
Tasks.org uses a fork of ical4android that allows start=due (but not start>due). I'm not aware of it causing any issues
