### ISSUE TITLE
Tasks: add tasks app package to PRODID

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#72]
Currently, we're adding the mutators (the calendar apps that edited an event) to the PRODID like this:

```
# VEVENT
PRODID:DAVx5/4.2.3.4-ose ical4j/3.2.5 (org.withouthat.acalendarplus)
```

so that we can see from the ICalendar which calendar app has created the event.

There's no equivalent for tasks and journals. I suggest to add the package name of the used tasks backend to the PRODID like this:

```
# VTODO
PRODID:DAVx5/4.2.3.4-ose ical4j/3.2.5 (tasks.app.here)
```

---

- [x] Move `userAgents` from `Event` up to `ICalendar`
- [x] Add task app package name from `taskList.provider` to `task.userAgents` in `AndroidTask.populateTask()`
- [x] Extract https://github.com/bitfireAT/ical4android/blob/6d87d43fca764c608fd0ef49b3a4cce032513a11/src/main/java/at/bitfire/ical4android/Event.kt#L213-L216 to a new method `ICalendar.prodId()` which generates the `PRODID` with the userAgents (instead of `var prodId`).
- [x] Call this `prodId()` method in `Event.write()` and `Task.write()`
- [x] Similarly add jtx Board package name to https://github.com/bitfireAT/ical4android/blob/6d87d43fca764c608fd0ef49b3a4cce032513a11/src/main/java/at/bitfire/ical4android/JtxICalObject.kt#L551
- [x] Adapt `PRODID` test in `TaskTest.testWrite()`

@patrickunterwegs Where should we add the test in JtxICalObjectTest?

**Comment by patrickunterwegs** [comment]
Hi @ArnyminerZ , @rfc2822 , 
there's only the authority in a constant available: 
const val AUTHORITY = "at.techbee.jtx.provider"

But I think it's better to keep the package name there and I would also leave it just hardcoded as it's the only place where it's needed in the code. 👍
